version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydb  # MongoDB URI for connection
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Exposes MongoDB default port
    volumes:
      - mongo-data:/data/db  # Persists MongoDB data between container restarts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
